version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/tinovyatkin/container-source-policy

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
