version: 2
project_name: container-source-policy

before:
  hooks:
    - go mod tidy

builds:
  - id: container-source-policy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/tinovyatkin/container-source-policy/internal/version.version={{.Version}} -X github.com/tinovyatkin/container-source-policy/internal/version.commit={{.Commit}}

archives:
  - id: container-source-policy
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}MacOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
